#!/usr/bin/env python

import rospy
import math
from franka_msgs.srv import jacobian_service

def derivative_matrix(req):
    theta_1 = req.joint_states[0]
    theta_2 = req.joint_states[1]
    theta_3 = req.joint_states[2]
    theta_4 = req.joint_states[3]
    theta_5 = req.joint_states[4]
    theta_6 = req.joint_states[5]
    theta_7 = req.joint_states[6]

    a11 = math.cos(theta_7)*(math.sin(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) - math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))) - math.sin(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))
    a12 = math.cos(theta_7)*(math.sin(theta_6)*(math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_1)*math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)) + math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_1)*math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5))) + math.sin(theta_7)*(math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_1)*math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_1)*math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3))
    a13 = math.cos(theta_7)*(math.cos(theta_6)*(math.sin(theta_5)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_4)*math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))) + math.sin(theta_4)*math.sin(theta_6)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))) - math.sin(theta_7)*(math.cos(theta_5)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_4)*math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))
    a14 = math.cos(theta_7)*(math.sin(theta_6)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.cos(theta_5)*math.cos(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2))) + math.sin(theta_5)*math.sin(theta_7)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2))
    a15 = math.cos(theta_6)*math.cos(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))) - math.sin(theta_7)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))
    a16 = math.cos(theta_7)*(math.cos(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))
    a17 = - math.cos(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))) - math.sin(theta_7)*(math.sin(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))

    a21 = math.cos(theta_7)*(math.sin(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))) - math.sin(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))
    a22 = math.sin(theta_7)*(math.sin(theta_5)*(math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) - math.cos(theta_5)*math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_3)) + math.cos(theta_7)*(math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) + math.sin(theta_6)*(math.cos(theta_2)*math.cos(theta_4)*math.sin(theta_1) + math.cos(theta_3)*math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)))
    a23 = math.sin(theta_7)*(math.cos(theta_5)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.cos(theta_4)*math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))) - math.cos(theta_7)*(math.cos(theta_6)*(math.sin(theta_5)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))) + math.sin(theta_4)*math.sin(theta_6)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))
    a24 = - math.cos(theta_7)*(math.sin(theta_6)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.cos(theta_5)*math.cos(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2))) - math.sin(theta_5)*math.sin(theta_7)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2))
    a25 = math.sin(theta_7)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))) - math.cos(theta_6)*math.cos(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))
    a26 = -math.cos(theta_7)*(math.cos(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) + math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))
    a27 = math.cos(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))) + math.sin(theta_7)*(math.sin(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) - math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))

    a31 = 0
    a32 = - math.sin(theta_7)*(math.sin(theta_5)*(math.sin(theta_2)*math.sin(theta_4) + math.cos(theta_2)*math.cos(theta_3)*math.cos(theta_4)) + math.cos(theta_2)*math.cos(theta_5)*math.sin(theta_3)) - math.cos(theta_7)*(math.cos(theta_6)*(math.cos(theta_5)*(math.sin(theta_2)*math.sin(theta_4) + math.cos(theta_2)*math.cos(theta_3)*math.cos(theta_4)) - math.cos(theta_2)*math.sin(theta_3)*math.sin(theta_5)) + math.sin(theta_6)*(math.cos(theta_4)*math.sin(theta_2) - math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_4)))
    a33 = math.cos(theta_7)*(math.cos(theta_6)*(math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_5) + math.cos(theta_4)*math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3)) - math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_4)*math.sin(theta_6)) - math.sin(theta_7)*(math.cos(theta_3)*math.cos(theta_5)*math.sin(theta_2) - math.cos(theta_4)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5))
    a34 = math.sin(theta_5)*math.sin(theta_7)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_7)*(math.sin(theta_6)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_5)*math.cos(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))
    a35 = math.sin(theta_7)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) - math.cos(theta_6)*math.cos(theta_7)*(math.sin(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3))
    a36 = -math.cos(theta_7)*(math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) - math.cos(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))
    a37 = math.cos(theta_7)*(math.sin(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3)) - math.sin(theta_7)*(math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) + math.sin(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))

    a41 = - math.cos(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))) - math.sin(theta_7)*(math.sin(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) - math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))
    a42 = math.cos(theta_7)*(math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_1)*math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_1)*math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3)) - math.sin(theta_7)*(math.sin(theta_6)*(math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_1)*math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)) + math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_1)*math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)))
    a43 = - math.sin(theta_7)*(math.cos(theta_6)*(math.sin(theta_5)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_4)*math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))) + math.sin(theta_4)*math.sin(theta_6)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))) - math.cos(theta_7)*(math.cos(theta_5)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_4)*math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))
    a44 = math.cos(theta_7)*math.sin(theta_5)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)) - math.sin(theta_7)*(math.sin(theta_6)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.cos(theta_5)*math.cos(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)))
    a45 = - math.cos(theta_7)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))) - math.cos(theta_6)*math.sin(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))
    a46 = -math.sin(theta_7)*(math.cos(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))
    a47 = math.sin(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))) - math.cos(theta_7)*(math.sin(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))

    a51 = - math.cos(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))) - math.sin(theta_7)*(math.sin(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))
    a52 = math.cos(theta_7)*(math.sin(theta_5)*(math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) - math.cos(theta_5)*math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_3)) - math.sin(theta_7)*(math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) + math.sin(theta_6)*(math.cos(theta_2)*math.cos(theta_4)*math.sin(theta_1) + math.cos(theta_3)*math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)))
    a53 = math.sin(theta_7)*(math.cos(theta_6)*(math.sin(theta_5)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))) + math.sin(theta_4)*math.sin(theta_6)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))) + math.cos(theta_7)*(math.cos(theta_5)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.cos(theta_4)*math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))
    a54 = math.sin(theta_7)*(math.sin(theta_6)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.cos(theta_5)*math.cos(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2))) - math.cos(theta_7)*math.sin(theta_5)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2))
    a55 = math.cos(theta_7)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))) + math.cos(theta_6)*math.sin(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))
    a56 = math.sin(theta_7)*(math.cos(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) + math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))
    a57 = math.cos(theta_7)*(math.sin(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) - math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))) - math.sin(theta_7)*(math.sin(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))
    
    a61 = 0
    a62 = math.sin(theta_7)*(math.cos(theta_6)*(math.cos(theta_5)*(math.sin(theta_2)*math.sin(theta_4) + math.cos(theta_2)*math.cos(theta_3)*math.cos(theta_4)) - math.cos(theta_2)*math.sin(theta_3)*math.sin(theta_5)) + math.sin(theta_6)*(math.cos(theta_4)*math.sin(theta_2) - math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_4))) - math.cos(theta_7)*(math.sin(theta_5)*(math.sin(theta_2)*math.sin(theta_4) + math.cos(theta_2)*math.cos(theta_3)*math.cos(theta_4)) + math.cos(theta_2)*math.cos(theta_5)*math.sin(theta_3))
    a63 = - math.sin(theta_7)*(math.cos(theta_6)*(math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_5) + math.cos(theta_4)*math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3)) - math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_4)*math.sin(theta_6)) - math.cos(theta_7)*(math.cos(theta_3)*math.cos(theta_5)*math.sin(theta_2) - math.cos(theta_4)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5))
    a64 = math.sin(theta_7)*(math.sin(theta_6)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_5)*math.cos(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4))) + math.cos(theta_7)*math.sin(theta_5)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4))
    a65 = math.cos(theta_7)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) + math.cos(theta_6)*math.sin(theta_7)*(math.sin(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3))
    a66 = math.sin(theta_7)*(math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) - math.cos(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))
    a67 = - math.sin(theta_7)*(math.sin(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3)) - math.cos(theta_7)*(math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) + math.sin(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))

    a71 = - math.cos(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) - math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))
    a72 = math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_1)*math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) - math.cos(theta_6)*(math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_1)*math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4))
    a73 = math.sin(theta_6)*(math.sin(theta_5)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_4)*math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))) - math.cos(theta_6)*math.sin(theta_4)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))
    a74 = math.cos(theta_5)*math.sin(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_6)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4))
    a75 = math.sin(theta_6)*(math.sin(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))
    a76 = math.sin(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))
    a77 = 0

    a81 = - math.cos(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)) - math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))
    a82 = math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) - math.cos(theta_6)*(math.cos(theta_2)*math.cos(theta_4)*math.sin(theta_1) + math.cos(theta_3)*math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4))
    a83 = math.cos(theta_6)*math.sin(theta_4)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)) - math.sin(theta_6)*(math.sin(theta_5)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))
    a84 = math.cos(theta_6)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*math.sin(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2))
    a85 = -math.sin(theta_6)*(math.sin(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))
    a86 = math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))) - math.sin(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2))
    a87 = 0

    a91 = 0
    a92 = math.cos(theta_6)*(math.cos(theta_4)*math.sin(theta_2) - math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_4)) - math.sin(theta_6)*(math.cos(theta_5)*(math.sin(theta_2)*math.sin(theta_4) + math.cos(theta_2)*math.cos(theta_3)*math.cos(theta_4)) - math.cos(theta_2)*math.sin(theta_3)*math.sin(theta_5))
    a93 = math.sin(theta_6)*(math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_5) + math.cos(theta_4)*math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3)) + math.cos(theta_6)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_4)
    a94 = math.cos(theta_6)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.cos(theta_5)*math.sin(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4))
    a95 = -math.sin(theta_6)*(math.sin(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3))
    a96 = math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)) + math.sin(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4))
    a97 = 0

    a101 = (11*math.sin(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)))/125 - (79*math.sin(theta_1)*math.sin(theta_2))/250 - (107*math.cos(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)))/1000 - (33*math.cos(theta_1)*math.sin(theta_3))/400 + (33*math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)))/400 - (11*math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))/125 + (48*math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)))/125 - (107*math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))/1000 - (48*math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2))/125 + (33*math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4))/400 - (33*math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1))/400
    a102 = (79*math.cos(theta_1)*math.cos(theta_2))/250 - (107*math.cos(theta_6)*(math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_1)*math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))/1000 + (11*math.sin(theta_6)*(math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_1)*math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))/125 + (11*math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_1)*math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)))/125 + (107*math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_1)*math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)))/1000 + (48*math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_4))/125 - (33*math.cos(theta_1)*math.cos(theta_3)*math.sin(theta_2))/400 - (33*math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_4))/400 + (33*math.cos(theta_1)*math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2))/400 + (48*math.cos(theta_1)*math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4))/125
    a103 = (33*math.cos(theta_4)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))/400 - (33*math.cos(theta_3)*math.sin(theta_1))/400 + (48*math.sin(theta_4)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))/125 + (11*math.cos(theta_6)*(math.sin(theta_5)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_4)*math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))/125 + (107*math.sin(theta_6)*(math.sin(theta_5)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_4)*math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))/1000 - (107*math.cos(theta_6)*math.sin(theta_4)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))/1000 + (11*math.sin(theta_4)*math.sin(theta_6)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3)))/125 - (33*math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))/400
    a104 = (11*math.sin(theta_6)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)))/125 - (107*math.cos(theta_6)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)))/1000 + (48*math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)))/125 - (33*math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)))/400 - (48*math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4))/125 + (11*math.cos(theta_5)*math.cos(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)))/125 + (107*math.cos(theta_5)*math.sin(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)))/1000 - (33*math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2))/400
    a105 = (11*math.cos(theta_6)*(math.sin(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))/125 + (107*math.sin(theta_6)*(math.sin(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))/1000
    a106 = (11*math.cos(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)))/125 + (107*math.sin(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)))/1000 - (107*math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))/1000 + (11*math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))/125
    a107 = 0

    a111 = (79*math.cos(theta_1)*math.sin(theta_2))/250 - (33*math.sin(theta_1)*math.sin(theta_3))/400 - (107*math.cos(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)))/1000 + (11*math.sin(theta_6)*(math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) + math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2)))/125 - (11*math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))/125 + (33*math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)))/400 - (107*math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)) - math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_3)*math.sin(theta_1) + math.cos(theta_1)*math.cos(theta_2)*math.sin(theta_3))))/1000 + (48*math.sin(theta_4)*(math.sin(theta_1)*math.sin(theta_3) - math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3)))/125 - (33*math.cos(theta_1)*math.sin(theta_2)*math.sin(theta_4))/400 + (33*math.cos(theta_1)*math.cos(theta_2)*math.cos(theta_3))/400 + (48*math.cos(theta_1)*math.cos(theta_4)*math.sin(theta_2))/125
    a112 = (11*math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)))/125 + (79*math.cos(theta_2)*math.sin(theta_1))/250 + (107*math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)))/1000 - (107*math.cos(theta_6)*(math.cos(theta_2)*math.cos(theta_4)*math.sin(theta_1) + math.cos(theta_3)*math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)))/1000 + (11*math.sin(theta_6)*(math.cos(theta_2)*math.cos(theta_4)*math.sin(theta_1) + math.cos(theta_3)*math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)))/125 - (33*math.cos(theta_3)*math.sin(theta_1)*math.sin(theta_2))/400 - (33*math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_4))/400 + (48*math.cos(theta_2)*math.cos(theta_4)*math.sin(theta_1))/125 + (33*math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2))/400 + (48*math.cos(theta_3)*math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4))/125
    a113 = (33*math.cos(theta_1)*math.cos(theta_3))/400 - (33*math.cos(theta_4)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))/400 - (48*math.sin(theta_4)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))/125 - (11*math.cos(theta_6)*(math.sin(theta_5)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))/125 - (107*math.sin(theta_6)*(math.sin(theta_5)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))/1000 - (33*math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))/400 + (107*math.cos(theta_6)*math.sin(theta_4)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))/1000 - (11*math.sin(theta_4)*math.sin(theta_6)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3)))/125
    a114 = (107*math.cos(theta_6)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)))/1000 - (11*math.sin(theta_6)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)))/125 - (48*math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)))/125 + (33*math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)))/400 - (33*math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2))/400 - (48*math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4))/125 - (11*math.cos(theta_5)*math.cos(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)))/125 - (107*math.cos(theta_5)*math.sin(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)))/1000
    a115 = - (11*math.cos(theta_6)*(math.sin(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))/125 - (107*math.sin(theta_6)*(math.sin(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) - math.cos(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))/1000
    a116 = (107*math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))/1000 - (107*math.sin(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)))/1000 - (11*math.cos(theta_6)*(math.sin(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) - math.cos(theta_4)*math.sin(theta_1)*math.sin(theta_2)))/125 - (11*math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_4)*(math.cos(theta_1)*math.sin(theta_3) + math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_1)) + math.sin(theta_1)*math.sin(theta_2)*math.sin(theta_4)) + math.sin(theta_5)*(math.cos(theta_1)*math.cos(theta_3) - math.cos(theta_2)*math.sin(theta_1)*math.sin(theta_3))))/125
    a117 = 0

    a121 = 0
    a122 = (33*math.sin(theta_2)*math.sin(theta_4))/400 - (33*math.cos(theta_2)*math.cos(theta_3))/400 - (48*math.cos(theta_4)*math.sin(theta_2))/125 - (79*math.sin(theta_2))/250 - (11*math.cos(theta_6)*(math.cos(theta_5)*(math.sin(theta_2)*math.sin(theta_4) + math.cos(theta_2)*math.cos(theta_3)*math.cos(theta_4)) - math.cos(theta_2)*math.sin(theta_3)*math.sin(theta_5)))/125 - (107*math.sin(theta_6)*(math.cos(theta_5)*(math.sin(theta_2)*math.sin(theta_4) + math.cos(theta_2)*math.cos(theta_3)*math.cos(theta_4)) - math.cos(theta_2)*math.sin(theta_3)*math.sin(theta_5)))/1000 + (107*math.cos(theta_6)*(math.cos(theta_4)*math.sin(theta_2) - math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_4)))/1000 - (11*math.sin(theta_6)*(math.cos(theta_4)*math.sin(theta_2) - math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_4)))/125 + (33*math.cos(theta_2)*math.cos(theta_3)*math.cos(theta_4))/400 + (48*math.cos(theta_2)*math.cos(theta_3)*math.sin(theta_4))/125
    a123 = (33*math.sin(theta_2)*math.sin(theta_3))/400 + (11*math.cos(theta_6)*(math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_5) + math.cos(theta_4)*math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3)))/125 + (107*math.sin(theta_6)*(math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_5) + math.cos(theta_4)*math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3)))/1000 - (33*math.cos(theta_4)*math.sin(theta_2)*math.sin(theta_3))/400 - (48*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_4))/125 + (107*math.cos(theta_6)*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_4))/1000 - (11*math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_4)*math.sin(theta_6))/125
    a124 = (107*math.cos(theta_6)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)))/1000 - (48*math.cos(theta_2)*math.sin(theta_4))/125 - (33*math.cos(theta_2)*math.cos(theta_4))/400 - (11*math.sin(theta_6)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)))/125 - (33*math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4))/400 + (11*math.cos(theta_5)*math.cos(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))/125 + (107*math.cos(theta_5)*math.sin(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))/1000 + (48*math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2))/125
    a125 = - (11*math.cos(theta_6)*(math.sin(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3)))/125 - (107*math.sin(theta_6)*(math.sin(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) - math.cos(theta_5)*math.sin(theta_2)*math.sin(theta_3)))/1000
    a126 = (107*math.cos(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)))/1000 - (11*math.sin(theta_6)*(math.cos(theta_5)*(math.cos(theta_2)*math.sin(theta_4) - math.cos(theta_3)*math.cos(theta_4)*math.sin(theta_2)) + math.sin(theta_2)*math.sin(theta_3)*math.sin(theta_5)))/125 + (11*math.cos(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))/125 + (107*math.sin(theta_6)*(math.cos(theta_2)*math.cos(theta_4) + math.cos(theta_3)*math.sin(theta_2)*math.sin(theta_4)))/1000
    a127 = 0

    a1 = [a11, a12, a13, a14, a15, a16 ,a17]
    a2 = [a21, a22, a23, a24, a25, a26, a27]
    a3 = [a31, a32, a33, a34, a35, a36, a37]
    a4 = [a41, a42, a43, a44, a45, a46, a47]
    a5 = [a51, a52, a53, a54, a55, a56, a57]   
    a6 = [a61, a62, a63, a64, a65, a66, a67]
    a7 = [a71, a72, a73, a74, a75, a76, a77]
    a8 = [a81, a82, a83, a84, a85, a86, a87]
    a9 = [a91, a92, a93, a94, a95, a96, a97]
    a10 = [a101, a102, a103, a104, a105, a106, a107]
    a11 = [a111, a112, a113, a114, a115, a116, a117]
    a12 = [a121, a122, a123, a124, a125, a126, a127]

    return a1, a2, a3, a4, a5, a6, a7, a8 ,a9, a10, a11, a12

if __name__ == '__main__':
    rospy.init_node('compute_another_jacobian')
    rospy.Service("/compute_another_jacobian", jacobian_service, derivative_matrix)
    print("Server started")
    rospy.spin()