#!/usr/bin/env python

import rospy
import math
from franka_msgs.srv import jacobian_service

def derivative_matrix(req):
    theta1 = req.joint_states[0]
    theta2 = req.joint_states[1]
    theta3 = req.joint_states[2]
    theta4 = req.joint_states[3]
    theta5 = req.joint_states[4]
    theta6 = req.joint_states[5]
    theta7 = req.joint_states[6]

    a11theta1 = (math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta7)-math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)
                -math.sin(theta3)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)-math.sin(theta5)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)*math.cos(theta7)+
                math.sin(theta7)*math.cos(theta1)*math.cos(theta3)*math.cos(theta5)-math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)-math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.cos(theta4)*math.cos(theta7)
                + math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta2)*math.cos(theta6)*math.cos(theta7)-math.sin(theta1)*math.sin(theta3)*math.sin(theta7)*math.cos(theta2)*math.cos(theta5)
                +math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta7)-math.sin(theta1)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7))
    #print(a11theta1)
    a11theta2 = (math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)+
                    math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)+
                    math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta7)+
                    math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta6)*math.cos(theta7)
                    -math.sin(theta2)*math.sin(theta3)*math.sin(theta7)*math.cos(theta1)*math.cos(theta5)+
                    math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)*math.cos(theta7)
                    -math.sin(theta2)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)
                    -math.sin(theta2)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7))
    #print(a11theta2)
    a11theta3 = (math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta3)*math.cos(theta7)
                    -math.sin(theta1)*math.sin(theta5)*math.sin(theta7)*math.cos(theta3)*math.cos(theta4)
                    -math.sin(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)+
                    math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta6)*math.cos(theta7)
                    -math.sin(theta1)*math.sin(theta3)*math.sin(theta7)*math.cos(theta5)
                    -math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)*math.cos(theta7)+
                    math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)+
                    math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta7)
                    -math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)
                    -math.sin(theta3)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7))

    a11theta4 = (math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.cos(theta4)*math.cos(theta7)+
                math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)+
                math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)+
                math.sin(theta2)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)+
                math.sin(theta2)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta7)
                -math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                -math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7))

    a11theta5 = (-math.sin(theta1)*math.sin(theta3)*math.sin(theta7)*math.cos(theta4)*math.cos(theta5)+
                    math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta4)*math.cos(theta6)*math.cos(theta7)
                    -math.sin(theta1)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                    -math.sin(theta1)*math.sin(theta5)*math.sin(theta7)*math.cos(theta3)+
                    math.sin(theta2)*math.sin(theta4)*math.sin(theta7)*math.cos(theta1)*math.cos(theta5)
                    -math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.cos(theta1)*math.cos(theta6)*math.cos(theta7)
                    -math.sin(theta3)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                    -math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)+
                    math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                    -math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)*math.cos(theta7)
                    )
    a11theta6 = (math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.cos(theta6)*math.cos(theta7)+
                    math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.cos(theta4)*math.cos(theta5)*math.cos(theta7)+
                    math.sin(theta1)*math.sin(theta5)*math.sin(theta6)*math.cos(theta3)*math.cos(theta7)
                    -math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta5)*math.cos(theta7)+
                    math.sin(theta2)*math.cos(theta1)*math.cos(theta4)*math.cos(theta6)*math.cos(theta7)+
                    math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta7)
                    -math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)*math.cos(theta7)
                    -math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta7)
                    )
    a11theta7 = (-math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)
                    -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta4)*math.cos(theta7)+
                    math.sin(theta1)*math.sin(theta3)*math.sin(theta7)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)+
                    math.sin(theta1)*math.sin(theta5)*math.sin(theta7)*math.cos(theta3)*math.cos(theta6)+
                    math.sin(theta1)*math.cos(theta3)*math.cos(theta5)*math.cos(theta7)+
                    math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.cos(theta1)*math.cos(theta7)
                    -math.sin(theta2)*math.sin(theta4)*math.sin(theta7)*math.cos(theta1)*math.cos(theta5)*math.cos(theta6)
                    -math.sin(theta2)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)+
                    math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta6)
                    +math.sin(theta3)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)*math.cos(theta7)
                    +math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                    +math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                    -math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6))

    a12theta1 = (-math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)
                    -math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta4)*math.cos(theta7)
                    +math.sin(theta3)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                    +math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)
                    +math.cos(theta1)*math.cos(theta3)*math.cos(theta5)*math.cos(theta7)
                    -math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.cos(theta7)
                    +math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta7)*math.cos(theta5)*math.cos(theta6)
                    +math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.sin(theta7)*math.cos(theta4)
                    -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta6)
                    -math.sin(theta1)*math.sin(theta3)*math.cos(theta2)*math.cos(theta5)*math.cos(theta7)
                    -math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)
                    -math.sin(theta1)*math.sin(theta5)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                    +math.sin(theta1)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                    )

    a12theta2 = (math.sin(theta4)*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta7)
                    -math.sin(theta4)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                    -math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)
                    -math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta6)
                    -math.sin(theta2)*math.sin(theta3)*math.cos(theta1)*math.cos(theta5)*math.cos(theta7)
                    -math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta3)
                    -math.sin(theta2)*math.sin(theta5)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                    +math.sin(theta2)*math.sin(theta7)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6))

    a12theta3 = (-math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta3)
                    -math.sin(theta1)*math.sin(theta5)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                    +math.sin(theta1)*math.sin(theta7)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                    -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta6)
                    -math.sin(theta1)*math.sin(theta3)*math.cos(theta5)*math.cos(theta7)
                    +math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                    +math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)*math.cos(theta7)
                    -math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)
                    -math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta7)
                    +math.sin(theta3)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                    )

    a12theta4 = (-math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.sin(theta7)*math.cos(theta4)
                    +math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta5)*math.cos(theta7)
                    -math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta7)*math.cos(theta5)*math.cos(theta6)
                    +math.sin(theta2)*math.sin(theta5)*math.cos(theta1)*math.cos(theta4)*math.cos(theta7)
                    -math.sin(theta2)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                    +math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)
                    +math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                    -math.sin(theta4)*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta7)
                    +math.sin(theta4)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)
                    )

    a12theta5 = (-math.sin(theta1)*math.sin(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta4)*math.cos(theta6)
                +math.sin(theta1)*math.sin(theta7)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta5)*math.cos(theta3)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta5)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta6)
                +math.sin(theta3)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta7)
                +math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta7)
                +math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                )


    a12theta6 = (-math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta7)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.sin(theta7)*math.cos(theta4)*math.cos(theta5)
                -math.sin(theta1)*math.sin(theta5)*math.sin(theta6)*math.sin(theta7)*math.cos(theta3)
                +math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta5)
                -math.sin(theta2)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)*math.cos(theta6)
                -math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)
                +math.sin(theta4)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                +math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                )


    a12theta7 = (-math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta4)
                +math.sin(theta1)*math.sin(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta5)*math.cos(theta3)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta7)*math.cos(theta3)*math.cos(theta5)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)
                -math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta2)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)*math.cos(theta7)
                +math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta3)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)
                +math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta7)
                -math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                )

    a13theta1 = (-math.sin(theta3)*math.sin(theta4)*math.cos(theta1)*math.cos(theta6)
                -math.sin(theta3)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)
                -math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta5)
                +math.sin(theta1)*math.sin(theta2)*math.cos(theta4)*math.cos(theta6)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)
                -math.sin(theta1)*math.sin(theta4)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5))


    a13theta2 = (math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)
                -math.cos(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta6)
                +math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)
                -math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)
                -math.sin(theta2)*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                )

    a13theta3 = (-math.sin(theta1)*math.sin(theta4)*math.cos(theta3)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta6)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)
                -math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                -math.sin(theta3)*math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta6)
                -math.sin(theta3)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)
                )

    a13theta4 = (-math.sin(theta1)*math.sin(theta3)*math.cos(theta4)*math.cos(theta6)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta5) 
                +math.sin(theta2)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)
                +math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta6)
                +math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                -math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)
                )

    a13theta5 = (
                math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta4)
                -math.sin(theta1)*math.sin(theta6)*math.cos(theta3)*math.cos(theta5)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)
            
                -math.sin(theta3)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)
            
                -math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                )

    a13theta6 = (math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)
                -math.sin(theta1)*math.sin(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta5)*math.cos(theta3)*math.cos(theta6)
                +math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta2)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)
                -math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta6)
                -math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                +math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                )
    a13theta7 = (0)

    a14theta1 = (0.088*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)
                -0.107*math.sin(theta3)*math.sin(theta4)*math.cos(theta1)*math.cos(theta6)
                +0.384*math.sin(theta3)*math.sin(theta4)*math.cos(theta1)
                -0.107*math.sin(theta3)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)
                -0.088*math.sin(theta3)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta3)*math.cos(theta1)*math.cos(theta4)
                -0.0825*math.sin(theta3)*math.cos(theta1)
                -0.107*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)
                -0.088*math.sin(theta5)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)
                -0.107*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta5)
                -0.088*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)
                -0.088*math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.cos(theta4)
                +0.107*math.sin(theta1)*math.sin(theta2)*math.cos(theta4)*math.cos(theta6)
                -0.384*math.sin(theta1)*math.sin(theta2)*math.cos(theta4) - 0.316*math.sin(theta1)*math.sin(theta2)
                +0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)
                +0.088*math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta2)*math.cos(theta6)
                +0.088*math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)
                -0.107*math.sin(theta1)*math.sin(theta4)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                +0.384*math.sin(theta1)*math.sin(theta4)*math.cos(theta2)*math.cos(theta3)
                -0.107*math.sin(theta1)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                -0.088*math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -0.0825*math.sin(theta1)*math.cos(theta2)*math.cos(theta3)
                )
    a14theta2 = (0.107*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)
                +0.088*math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.sin(theta4)*math.cos(theta1)*math.cos(theta2)
                +0.088*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)
                -0.107*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta6)
                +0.384*math.cos(theta1)*math.cos(theta2)*math.cos(theta4) + 0.316*math.cos(theta1)*math.cos(theta2)
                +0.107*math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)
                +0.088*math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta6)
                +0.088*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)
                -0.107*math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)
                +0.384*math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta3)
                -0.107*math.sin(theta2)*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                -0.088*math.sin(theta2)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta2)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)
                -0.0825*math.sin(theta2)*math.cos(theta1)*math.cos(theta3)
                )
    a14theta3 = (0.088*math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta3)
                -0.107*math.sin(theta1)*math.sin(theta4)*math.cos(theta3)*math.cos(theta6)
                +0.384*math.sin(theta1)*math.sin(theta4)*math.cos(theta3)
                -0.107*math.sin(theta1)*math.sin(theta6)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                -0.088*math.sin(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta1)*math.cos(theta3)*math.cos(theta4)
                -0.0825*math.sin(theta1)*math.cos(theta3)
                +0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)
                +0.088*math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta6)
                -0.107*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                -0.088*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                +0.088*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)
                -0.107*math.sin(theta3)*math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta6)
                +0.384*math.sin(theta3)*math.sin(theta4)*math.cos(theta1)*math.cos(theta2)
                -0.107*math.sin(theta3)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)
                -0.088*math.sin(theta3)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta3)*math.cos(theta1)*math.cos(theta2)*math.cos(theta4)
                -0.0825*math.sin(theta3)*math.cos(theta1)*math.cos(theta2)
                )
    a14theta4 = (0.088*math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.cos(theta4)
                -0.107*math.sin(theta1)*math.sin(theta3)*math.cos(theta4)*math.cos(theta6)
                +0.384*math.sin(theta1)*math.sin(theta3)*math.cos(theta4)
                +0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta5)
                +0.088*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)
                +0.107*math.sin(theta2)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)
                +0.088*math.sin(theta2)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.sin(theta2)*math.cos(theta1)*math.cos(theta4)
                -0.088*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)
                +0.107*math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta6)
                -0.384*math.sin(theta2)*math.sin(theta4)*math.cos(theta1)
                -0.088*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                +0.107*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                -0.384*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -0.107*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)
                -0.088*math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                )
    a14theta5 = (0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta4)
                +0.088*math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta4)*math.cos(theta6)
                -0.107*math.sin(theta1)*math.sin(theta6)*math.cos(theta3)*math.cos(theta5)
                -0.088*math.sin(theta1)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)
                -0.107*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)
                -0.088*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.cos(theta1)*math.cos(theta6)
                -0.107*math.sin(theta3)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)
                -0.088*math.sin(theta3)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                -0.107*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -0.088*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                )
    a14theta6 = (0.088*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.cos(theta6)
                +0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)
                -0.107*math.sin(theta1)*math.sin(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.088*math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.cos(theta4)*math.cos(theta5)
                -0.107*math.sin(theta1)*math.sin(theta5)*math.cos(theta3)*math.cos(theta6)
                +0.088*math.sin(theta1)*math.sin(theta5)*math.sin(theta6)*math.cos(theta3)
                +0.107*math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta5)*math.cos(theta6)
                -0.088*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta5)
                +0.088*math.sin(theta2)*math.cos(theta1)*math.cos(theta4)*math.cos(theta6)
                +0.107*math.sin(theta2)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)
                -0.107*math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta6)
                +0.088*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)
                -0.088*math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                -0.107*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                +0.107*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.088*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                )
    a14theta7 = (0)


    a21theta1 = (math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)
                +math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta3)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)
                -math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta7)
                +math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                +math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta4)
                -math.sin(theta1)*math.sin(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta5)*math.cos(theta3)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta7)*math.cos(theta3)*math.cos(theta5))
    a21theta2 = (math.sin(theta1)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)
                +math.sin(theta1)*math.sin(theta4)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta6)*math.cos(theta2)*math.cos(theta4)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta3)*math.sin(theta7)*math.cos(theta5)
                +math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta3)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta5)*math.sin(theta7)*math.cos(theta3)*math.cos(theta4)
                -math.sin(theta1)*math.sin(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                )
    a21theta3 = (-math.sin(theta1)*math.sin(theta5)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta4)
                -math.sin(theta1)*math.sin(theta3)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)*math.cos(theta7)
                +math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)
                +math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta3)*math.sin(theta7)*math.cos(theta1)*math.cos(theta5)
                )
    a21theta4 = (math.sin(theta1)*math.sin(theta2)*math.sin(theta5)*math.sin(theta7)*math.cos(theta4)
                +math.sin(theta1)*math.sin(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)
                -math.sin(theta1)*math.sin(theta4)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta3)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta3)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)
                -math.sin(theta3)*math.sin(theta4)*math.cos(theta1)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                )
    a21theta5 = (math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta7)*math.cos(theta5)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta3)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)
                +math.sin(theta1)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                -math.sin(theta1)*math.sin(theta5)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta3)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)
                -math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta4)*math.cos(theta6)*math.cos(theta7)
                +math.cos(theta1)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta3)
                )
    a21theta6 = (-math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta5)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta2)*math.cos(theta4)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta4)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta7)
                -math.sin(theta3)*math.sin(theta4)*math.cos(theta1)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta3)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta7)
                -math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)*math.cos(theta7)
                )
    a21theta7 = (math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta7)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.sin(theta7)*math.cos(theta4)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta6)
                +math.sin(theta1)*math.sin(theta3)*math.cos(theta2)*math.cos(theta5)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)
                +math.sin(theta1)*math.sin(theta5)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)
                +math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta3)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)
                -math.cos(theta1)*math.cos(theta3)*math.cos(theta5)*math.cos(theta7)
                )

    a22theta1 = (math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.cos(theta1)*math.cos(theta7)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta7)*math.cos(theta1)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta2)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)
                +math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta6)
                +math.sin(theta3)*math.cos(theta1)*math.cos(theta2)*math.cos(theta5)*math.cos(theta7)
                +math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                +math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta7)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta4)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta7)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta1)*math.sin(theta5)*math.sin(theta7)*math.cos(theta3)*math.cos(theta6)
                +math.sin(theta1)*math.cos(theta3)*math.cos(theta5)*math.cos(theta7)
                )
    a22theta2 = (math.sin(theta1)*math.sin(theta4)*math.sin(theta5)*math.cos(theta2)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta4)*math.sin(theta7)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta6)*math.sin(theta7)*math.cos(theta2)*math.cos(theta4)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta3)*math.cos(theta5)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta3)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta5)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta2)*math.sin(theta7)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                )
    a22theta3 = (math.sin(theta1)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                +math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta2)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta2)*math.cos(theta4)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta7)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta3)
                +math.sin(theta5)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta7)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta6)
                +math.sin(theta3)*math.cos(theta1)*math.cos(theta5)*math.cos(theta7)
                )
    a22theta4 = (math.sin(theta1)*math.sin(theta2)*math.sin(theta5)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta7)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)
                +math.sin(theta1)*math.sin(theta6)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -math.sin(theta1)*math.sin(theta4)*math.sin(theta5)*math.cos(theta2)*math.cos(theta3)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta4)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta3)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)
                -math.sin(theta3)*math.sin(theta4)*math.sin(theta5)*math.cos(theta1)*math.cos(theta7)
                +math.sin(theta3)*math.sin(theta4)*math.sin(theta7)*math.cos(theta1)*math.cos(theta5)*math.cos(theta6)
                )
    a22theta5 = (math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta5)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta6)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta7)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta2)*math.cos(theta7)
                +math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                +math.sin(theta3)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta7)
                +math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)*math.cos(theta6)
                -math.sin(theta7)*math.cos(theta1)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta5)*math.cos(theta1)*math.cos(theta3)*math.cos(theta7)
                )
    a22theta6 = (math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta5)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta7)*math.cos(theta4)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.sin(theta7)*math.cos(theta2)
                +math.sin(theta1)*math.sin(theta4)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                +math.sin(theta1)*math.sin(theta6)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                +math.sin(theta3)*math.sin(theta4)*math.sin(theta7)*math.cos(theta1)*math.cos(theta6)
                +math.sin(theta3)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)
                +math.sin(theta5)*math.sin(theta6)*math.sin(theta7)*math.cos(theta1)*math.cos(theta3)
                )
    a22theta7 = (-math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.cos(theta4)*math.cos(theta7)
                +math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta2)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta7)*math.cos(theta2)*math.cos(theta5)
                +math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta7)
                -math.sin(theta1)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta7)
                -math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta1)*math.cos(theta4)
                -math.sin(theta3)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta5)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta7)*math.cos(theta1)*math.cos(theta3)*math.cos(theta5)
                )
    a23theta1 = (math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta5)
                -math.sin(theta2)*math.cos(theta1)*math.cos(theta4)*math.cos(theta6)
                -math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)
                +math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                +math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.cos(theta4)*math.cos(theta5)
                -math.sin(theta1)*math.sin(theta5)*math.sin(theta6)*math.cos(theta3)
                )
    a23theta2 = (math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta5)
                -math.sin(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta6)
                +math.sin(theta1)*math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta3)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5))
    a23theta3 = (-math.sin(theta1)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.cos(theta2)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)
                +math.sin(theta4)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)
                +math.sin(theta6)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                )       
    a23theta4 = (math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.cos(theta4)*math.cos(theta5)
                +math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta6)
                +math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)
                +math.sin(theta3)*math.cos(theta1)*math.cos(theta4)*math.cos(theta6)
                -math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta5)
                )
    a23theta5 = (-math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta6)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.cos(theta2)*math.cos(theta5)
                -math.sin(theta1)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)
                +math.sin(theta6)*math.cos(theta1)*math.cos(theta3)*math.cos(theta5)
                )
    a23theta6 = (math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.cos(theta4)
                -math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta2)*math.cos(theta6)
                -math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)
                +math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)
                +math.sin(theta3)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta5)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)
                )
    a23theta7 = (0)
    a24theta1 = (0.107*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta5)
                +0.088*math.sin(theta2)*math.sin(theta4)*math.cos(theta1)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta2)*math.sin(theta4)*math.cos(theta1)
                +0.088*math.sin(theta2)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)
                +0.107*math.sin(theta2)*math.cos(theta1)*math.cos(theta4)*math.cos(theta6)
                +0.384*math.sin(theta2)*math.cos(theta1)*math.cos(theta4)
                +0.316*math.sin(theta2)*math.cos(theta1)
                +0.107*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)
                +0.088*math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta2)*math.cos(theta6)
                +0.088*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                +0.107*math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                +0.384*math.sin(theta4)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                +0.107*math.sin(theta6)*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                +0.088*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                +0.0825*math.cos(theta1)*math.cos(theta2)*math.cos(theta3)
                -0.088*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)
                -0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.cos(theta6)
                -0.384*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)
                -0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.cos(theta4)*math.cos(theta5)
                -0.088*math.sin(theta1)*math.sin(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.sin(theta1)*math.sin(theta3)*math.cos(theta4)
                -0.0825*math.sin(theta1)*math.sin(theta3)
                -0.107*math.sin(theta1)*math.sin(theta5)*math.sin(theta6)*math.cos(theta3)
                -0.088*math.sin(theta1)*math.sin(theta5)*math.cos(theta3)*math.cos(theta6)
                )
    a24theta2 = (0.107*math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta5)
                +0.088*math.sin(theta1)*math.sin(theta4)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta1)*math.sin(theta4)*math.cos(theta2)
                +0.088*math.sin(theta1)*math.sin(theta6)*math.cos(theta2)*math.cos(theta4)
                +0.107*math.sin(theta1)*math.cos(theta2)*math.cos(theta4)*math.cos(theta6)
                +0.384*math.sin(theta1)*math.cos(theta2)*math.cos(theta4)
                +0.316*math.sin(theta1)*math.cos(theta2)
                -0.107*math.sin(theta1)*math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)
                -0.088*math.sin(theta1)*math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.cos(theta6)
                -0.088*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta3)
                -0.107*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta3)*math.cos(theta6)
                -0.384*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta3)
                -0.107*math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                -0.088*math.sin(theta1)*math.sin(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.sin(theta1)*math.sin(theta2)*math.cos(theta3)*math.cos(theta4)
                -0.0825*math.sin(theta1)*math.sin(theta2)*math.cos(theta3)
                )
    a24theta3 = (0.107*math.sin(theta1)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)
                +0.088*math.sin(theta1)*math.sin(theta5)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                -0.088*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)
                -0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.cos(theta2)*math.cos(theta6)
                -0.384*math.sin(theta1)*math.sin(theta3)*math.sin(theta4)*math.cos(theta2)
                -0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)
                -0.088*math.sin(theta1)*math.sin(theta3)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.sin(theta1)*math.sin(theta3)*math.cos(theta2)*math.cos(theta4)
                -0.0825*math.sin(theta1)*math.sin(theta3)*math.cos(theta2)
                +0.088*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)
                +0.107*math.sin(theta4)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)
                +0.384*math.sin(theta4)*math.cos(theta1)*math.cos(theta3)
                +0.107*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                +0.088*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.cos(theta1)*math.cos(theta3)*math.cos(theta4)
                +0.0825*math.cos(theta1)*math.cos(theta3)
                -0.107*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)
                -0.088*math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta6)
                )       
    a24theta4 = (0.107*math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.cos(theta4)*math.cos(theta5)
                +0.088*math.sin(theta1)*math.sin(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta1)*math.sin(theta2)*math.cos(theta4)
                -0.088*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)
                -0.107*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta6)
                -0.384*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)
                +0.088*math.sin(theta1)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                +0.107*math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                +0.384*math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -0.107*math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)
                -0.088*math.sin(theta1)*math.sin(theta4)*math.cos(theta2)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.sin(theta1)*math.sin(theta4)*math.cos(theta2)*math.cos(theta3)
                +0.088*math.sin(theta3)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)
                +0.107*math.sin(theta3)*math.cos(theta1)*math.cos(theta4)*math.cos(theta6)
                +0.384*math.sin(theta3)*math.cos(theta1)*math.cos(theta4)
                -0.107*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)*math.cos(theta5)
                -0.088*math.sin(theta3)*math.sin(theta4)*math.cos(theta1)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.sin(theta3)*math.sin(theta4)*math.cos(theta1))
    a24theta5 = (-0.107*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta6)
                -0.088*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.cos(theta6)
                +0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta6)*math.cos(theta2)*math.cos(theta5)
                +0.088*math.sin(theta1)*math.sin(theta3)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                -0.107*math.sin(theta1)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -0.088*math.sin(theta1)*math.sin(theta5)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                -0.107*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)
                -0.088*math.sin(theta3)*math.sin(theta5)*math.cos(theta1)*math.cos(theta4)*math.cos(theta6)
                +0.107*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)*math.cos(theta5)
                +0.088*math.cos(theta1)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)
                )
    a24theta6 = (0.107*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.088*math.sin(theta1)*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta5)
                +0.088*math.sin(theta1)*math.sin(theta2)*math.cos(theta4)*math.cos(theta6)
                -0.107*math.sin(theta1)*math.sin(theta2)*math.sin(theta6)*math.cos(theta4)
                +0.107*math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.cos(theta2)*math.cos(theta6)
                -0.088*math.sin(theta1)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)
                +0.088*math.sin(theta1)*math.sin(theta4)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                -0.107*math.sin(theta1)*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)
                +0.107*math.sin(theta1)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.088*math.sin(theta1)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                +0.088*math.sin(theta3)*math.sin(theta4)*math.cos(theta1)*math.cos(theta6)
                -0.107*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta1)
                +0.107*math.sin(theta3)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.088*math.sin(theta3)*math.sin(theta6)*math.cos(theta1)*math.cos(theta4)*math.cos(theta5)
                +0.107*math.sin(theta5)*math.cos(theta1)*math.cos(theta3)*math.cos(theta6)
                -0.088*math.sin(theta5)*math.sin(theta6)*math.cos(theta1)*math.cos(theta3)
                )
    a24theta7 = (0)

    a31theta1 = (0)
    a31theta2 = (math.sin(theta3)*math.sin(theta5)*math.cos(theta2)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta3)*math.sin(theta7)*math.cos(theta2)*math.cos(theta5)
                +math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta7)
                -math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)
                -math.sin(theta2)*math.sin(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta2)*math.sin(theta6)*math.cos(theta4)*math.cos(theta7)
                )
    a31theta3 = (math.sin(theta2)*math.sin(theta5)*math.cos(theta3)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta2)*math.sin(theta7)*math.cos(theta3)*math.cos(theta5)
                -math.sin(theta2)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta4)
                +math.sin(theta2)*math.sin(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                )       
    a31theta4 = (math.sin(theta2)*math.sin(theta6)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta3)
                +math.sin(theta2)*math.sin(theta4)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta4)
                +math.cos(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta7)
                )
    a31theta5 = (math.sin(theta2)*math.sin(theta3)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)
                -math.sin(theta2)*math.sin(theta7)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                +math.sin(theta2)*math.sin(theta5)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta4)*math.sin(theta7)*math.cos(theta2)*math.cos(theta5)
                -math.sin(theta4)*math.sin(theta5)*math.cos(theta2)*math.cos(theta6)*math.cos(theta7)
                )
    a31theta6 = (-math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta4)*math.cos(theta3)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta6)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta7)
                -math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta5)*math.cos(theta7)
                +math.cos(theta2)*math.cos(theta4)*math.cos(theta6)*math.cos(theta7)
                )
    a31theta7 = (-math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta6)
                -math.sin(theta2)*math.sin(theta3)*math.cos(theta5)*math.cos(theta7)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta3)
                -math.sin(theta2)*math.sin(theta5)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta7)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta4)*math.sin(theta5)*math.cos(theta2)*math.cos(theta7)
                -math.sin(theta4)*math.sin(theta7)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta6)*math.sin(theta7)*math.cos(theta2)*math.cos(theta4)
                )

    a32theta1 = (0)
    a32theta2 = (-math.sin(theta3)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta6)
                -math.sin(theta3)*math.cos(theta2)*math.cos(theta5)*math.cos(theta7)
                -math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta2)*math.cos(theta3)
                -math.sin(theta5)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta7)
                +math.sin(theta7)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta4)*math.sin(theta7)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta2)*math.sin(theta6)*math.sin(theta7)*math.cos(theta4)
                )
    a32theta3 = (-math.sin(theta2)*math.sin(theta5)*math.sin(theta7)*math.cos(theta3)*math.cos(theta6)
                -math.sin(theta2)*math.cos(theta3)*math.cos(theta5)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)*math.sin(theta7)
                +math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta2)*math.sin(theta3)*math.sin(theta7)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                )       
    a32theta4 = (-math.sin(theta2)*math.sin(theta6)*math.sin(theta7)*math.cos(theta3)*math.cos(theta4)
                +math.sin(theta2)*math.sin(theta4)*math.sin(theta5)*math.cos(theta3)*math.cos(theta7)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta7)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta5)*math.cos(theta2)*math.cos(theta4)*math.cos(theta7)
                -math.sin(theta7)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta2)
                )
    a32theta5 = (-math.sin(theta2)*math.sin(theta3)*math.sin(theta7)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.cos(theta7)
                -math.sin(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta7)
                -math.sin(theta2)*math.sin(theta5)*math.sin(theta7)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                +math.sin(theta4)*math.cos(theta2)*math.cos(theta5)*math.cos(theta7)
                +math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)*math.cos(theta6)
                )
    a32theta6 = (math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.sin(theta7)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta7)*math.cos(theta3)*math.cos(theta6)
                -math.sin(theta2)*math.sin(theta6)*math.sin(theta7)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                +math.sin(theta4)*math.sin(theta6)*math.sin(theta7)*math.cos(theta2)*math.cos(theta5)
                -math.sin(theta7)*math.cos(theta2)*math.cos(theta4)*math.cos(theta6)
                )
    a32theta7 = (-math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.cos(theta6)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta3)*math.sin(theta7)*math.cos(theta5)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta3)*math.cos(theta7)
                +math.sin(theta2)*math.sin(theta5)*math.sin(theta7)*math.cos(theta3)*math.cos(theta4)
                +math.sin(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta4)*math.sin(theta5)*math.sin(theta7)*math.cos(theta2)
                -math.sin(theta4)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)*math.cos(theta7)
                -math.sin(theta6)*math.cos(theta2)*math.cos(theta4)*math.cos(theta7)
                )

    a33theta1 = (0)
    a33theta2 = (math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)
                -math.sin(theta4)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                -math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                -math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta5)
                +math.sin(theta2)*math.cos(theta4)*math.cos(theta6)
                )
    a33theta3 = (math.sin(theta2)*math.sin(theta5)*math.sin(theta6)*math.cos(theta3)
                +math.sin(theta2)*math.sin(theta3)*math.sin(theta4)*math.cos(theta6)
                +math.sin(theta2)*math.sin(theta3)*math.sin(theta6)*math.cos(theta4)*math.cos(theta5)
                )       
    a33theta4 = (-math.sin(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                +math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta3)*math.cos(theta5)
                +math.sin(theta6)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)
                +math.sin(theta4)*math.cos(theta2)*math.cos(theta6)
                )
    a33theta5 = (math.sin(theta2)*math.sin(theta3)*math.sin(theta6)*math.cos(theta5)
                +math.sin(theta2)*math.sin(theta5)*math.sin(theta6)*math.cos(theta3)*math.cos(theta4)
                -math.sin(theta4)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2))

    a33theta6 = (math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.cos(theta6)
                +math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta3)
                -math.sin(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta4)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                +math.sin(theta6)*math.cos(theta2)*math.cos(theta4)
                )
    a33theta7 = (0)

    a34theta1 = (0)
    a34theta2 = (0.107*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)
                +0.088*math.sin(theta3)*math.sin(theta5)*math.cos(theta2)*math.cos(theta6)
                +0.088*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)
                -0.107*math.sin(theta4)*math.cos(theta2)*math.cos(theta3)*math.cos(theta6)
                +0.384*math.sin(theta4)*math.cos(theta2)*math.cos(theta3)
                -0.107*math.sin(theta6)*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                -0.088*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.cos(theta2)*math.cos(theta3)*math.cos(theta4)
                -0.0825*math.cos(theta2)*math.cos(theta3)
                -0.107*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta5)
                -0.088*math.sin(theta2)*math.sin(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.0825*math.sin(theta2)*math.sin(theta4)
                -0.088*math.sin(theta2)*math.sin(theta6)*math.cos(theta4)
                +0.107*math.sin(theta2)*math.cos(theta4)*math.cos(theta6)
                -0.384*math.sin(theta2)*math.cos(theta4)
                -0.316*math.sin(theta2)
                )
    a34theta3 = (0.107*math.sin(theta2)*math.sin(theta5)*math.sin(theta6)*math.cos(theta3)
                +0.088*math.sin(theta2)*math.sin(theta5)*math.cos(theta3)*math.cos(theta6)
                -0.088*math.sin(theta2)*math.sin(theta3)*math.sin(theta4)*math.sin(theta6)
                +0.107*math.sin(theta2)*math.sin(theta3)*math.sin(theta4)*math.cos(theta6)
                -0.384*math.sin(theta2)*math.sin(theta3)*math.sin(theta4)
                +0.107*math.sin(theta2)*math.sin(theta3)*math.sin(theta6)*math.cos(theta4)*math.cos(theta5)
                +0.088*math.sin(theta2)*math.sin(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.sin(theta2)*math.sin(theta3)*math.cos(theta4)
                +0.0825*math.sin(theta2)*math.sin(theta3)
                )       
    a34theta4 = (0.088*math.sin(theta2)*math.sin(theta6)*math.cos(theta3)*math.cos(theta4)
                -0.107*math.sin(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                +0.384*math.sin(theta2)*math.cos(theta3)*math.cos(theta4)
                +0.107*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta3)*math.cos(theta5)
                +0.088*math.sin(theta2)*math.sin(theta4)*math.cos(theta3)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.sin(theta2)*math.sin(theta4)*math.cos(theta3)
                +0.107*math.sin(theta6)*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)
                +0.088*math.cos(theta2)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                -0.0825*math.cos(theta2)*math.cos(theta4)
                -0.088*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)
                +0.107*math.sin(theta4)*math.cos(theta2)*math.cos(theta6)
                -0.384*math.sin(theta4)*math.cos(theta2)
                )
    a34theta5 = (0.107*math.sin(theta2)*math.sin(theta3)*math.sin(theta6)*math.cos(theta5)
                +0.088*math.sin(theta2)*math.sin(theta3)*math.cos(theta5)*math.cos(theta6)
                +0.107*math.sin(theta2)*math.sin(theta5)*math.sin(theta6)*math.cos(theta3)*math.cos(theta4)
                +0.088*math.sin(theta2)*math.sin(theta5)*math.cos(theta3)*math.cos(theta4)*math.cos(theta6)
                -0.107*math.sin(theta4)*math.sin(theta5)*math.sin(theta6)*math.cos(theta2)
                -0.088*math.sin(theta4)*math.sin(theta5)*math.cos(theta2)*math.cos(theta6)
                )

    a34theta6 = (0.107*math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.cos(theta6)
                -0.088*math.sin(theta2)*math.sin(theta3)*math.sin(theta5)*math.sin(theta6)
                +0.088*math.sin(theta2)*math.sin(theta4)*math.cos(theta3)*math.cos(theta6)
                +0.107*math.sin(theta2)*math.sin(theta4)*math.sin(theta6)*math.cos(theta3)
                -0.107*math.sin(theta2)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)*math.cos(theta6)
                +0.088*math.sin(theta2)*math.sin(theta6)*math.cos(theta3)*math.cos(theta4)*math.cos(theta5)
                +0.107*math.sin(theta4)*math.cos(theta2)*math.cos(theta5)*math.cos(theta6)
                -0.088*math.sin(theta4)*math.sin(theta6)*math.cos(theta2)*math.cos(theta5)
                +0.088*math.cos(theta2)*math.cos(theta4)*math.cos(theta6)
                +0.107*math.sin(theta6)*math.cos(theta2)*math.cos(theta4)
                )
    a34theta7 = (0)
    a11 = [a11theta1,a11theta2,a11theta3,a11theta4,a11theta5,a11theta6,a11theta7]
    a21 = [a21theta1,a21theta2,a21theta3,a21theta4,a21theta5,a21theta6,a21theta7]
    a31 = [a31theta1,a31theta2,a31theta3,a31theta4,a31theta5,a31theta6,a31theta7]
    a12 = [a12theta1,a12theta2,a12theta3,a12theta4,a12theta5,a12theta6,a12theta7]
    a22 = [a22theta1,a22theta2,a22theta3,a22theta4,a22theta5,a22theta6,a22theta7]
    a32 = [a32theta1,a32theta2,a32theta3,a32theta4,a32theta5,a32theta6,a32theta7]
    a13 = [a13theta1,a13theta2,a13theta3,a13theta4,a13theta5,a13theta6,a13theta7]
    a23 = [a23theta1,a23theta2,a23theta3,a23theta4,a23theta5,a23theta6,a23theta7]
    a33 = [a33theta1,a33theta2,a33theta3,a33theta4,a33theta5,a33theta6,a33theta7]
    a14 = [a14theta1,a14theta2,a14theta3,a14theta4,a14theta5,a14theta6,a14theta7]
    a24 = [a24theta1,a24theta2,a24theta3,a24theta4,a24theta5,a24theta6,a24theta7]
    a34 = [a34theta1,a34theta2,a34theta3,a34theta4,a34theta5,a34theta6,a34theta7]

    print(a11,a21,a31,a12,a22,a32,a13,a23,a33,a14,a24,a34
)
    

    return a11,a21,a31,a12,a22,a32,a13,a23,a33,a14,a24,a34

if __name__ == '__main__':
    rospy.init_node('compute_jacobian')
    rospy.Service("/compute_jacobian", jacobian_service, derivative_matrix)
    print("Server started")
    rospy.spin()

